<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link href="https://fonts.googleapis.com/css?family=Caveat|Vast+Shadow&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/repertoire.css">
    <script src="https://kit.fontawesome.com/ac5628c3f3.js" crossorigin="anonymous"></script>
</head>
<body>
	<main>
        <h1><i class="fas fa-book"></i> Mon répertoire</h1>
        <section>
            <?php if(empty($contacts) == false): ?>
                <!-- Formulaire listant toutes les contacts existants avec possibilité de suppression. -->
                <form class="common-form" action="remove.php" method="POST">									
                    <table class="table-contact">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Nom</th>
                                <th>Adresse</th>
                                <th>Email</th>
                                <th>Téléphone</th>
                                <th></th>                                  
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($contacts as $index => $contactData): ?>
                                <tr>
                                    <td><input id="contact-<?= $index ?>" type="checkbox" name="indexes[]" value="<?= $index ?>"></td>
                                    <td><?= $contactData[0] ?> <?= $contactData[1] ?></td>
                                    <td><?= $contactData[2] ?></td>
                                    <td><?= $contactData[3] ?></td>
                                    <td><?= $contactData[4] ?></td>
                                    <td><a href="modify.php?index=<?= $index ?>">Modifier</a></td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                    <input type="submit" value="Supprimer" title="Supprimer les contacts sélectionnés">
                </form>
            <?php endif ?>
        </section>
        <hr>		
        <section>
            <!-- Formulaire d'ajout de contact -->
            <form class="common-form" action="add.php" method="POST">
                <fieldset>
                    <legend>Informations sur la tâche</legend>
                    <ul>
                        <li>
                            <label for="nom">Nom :</label>
                            <input id="nom" name="lastname" type="text" value="<?= $contact[0] ?? '' ?>">
                        </li>
                        <li>
                            <label for="prenom">Prénom :</label>
                            <input id="prenom" name="firstname" type="text" value="<?= $contact[1] ?? '' ?>">
                        </li>
                        <li>
                            <label for="adresse">Adresse :</label>
                            <input id="adresse" name="address" type="text" value="<?= $contact[2] ?? '' ?>">
                        </li>
                        <li>
                            <label for="mail">Email :</label>
                            <input id="mail" name="email" type="text" value="<?= $contact[3] ?? '' ?>">
                        </li>
                        <li>
                            <label for="telephone">Téléphone :</label>
                            <input id="telephone" name="phone" type="text" value="<?= $contact[4] ?? '' ?>">
                        </li>                        
                        <li>
                            <input type="submit" value="Ajouter" title="Ajouter un nouveau contact">
                        </li>
                    </ul>
                </fieldset>
            </form>
        </section>
    </main>
</body>
</html>